dnd-side-project/dnd-5th-5-frontend

- src/components/MainComponent.js
- src/components/main/MainComponent.js
- src/components/main/Modal.js
- src/components/main/Style.js
- src/pages/MainPage.js
> Feature: 모달

- src/App.js
> Fix: 헤더 제거

- src/components/mypage/MyPageComponent.js
> Fix: 헤더 변경

- public/index.html
> Fix: mixed contents 해결

- public/index.html
- src/components/auth/SocialLogin.js
- src/components/modal/FriendModal.js
- src/containers/auth/SocialLoginContainer.js
- src/lib/api/client.js
1. 로그인 과정 수정 (기존에는 !duplicatedData 에서 duplicatedData 가 true/false로 나눔)
2. 로그인 과정에 쓰인 로컬 스토리지를 세션 스토리지로 변경
#45
> Fix: 로그인 과정

- src/components/auth/SocialLogin.js
- src/components/auth/style.js
> Style: 닉네임 모달 수정

- package.json
- src/containers/select/SelectContainer.js
- yarn.lock
1. react-responsive 삭제
2. .env 수정
#54
> Fix: mixed-contents, 오류 수정

- src/components/main/MainComponent.js
1. 메인 페이지 데스크탑 UI
2. 모바일 UI 위치 조정
#37
> Style: 메인 페이지

- src/components/alacard/AlaCardListComponent.js
- src/components/common/Header.js
- src/hooks/useOwner.js
- src/router/PrivateRoute.js
- src/router/Router.js
- src/router/SettingRoute.js
1. 프라이빗 라우터 (로그인 관련)
2. 세팅 라우터 (본인 세팅 페이지가 아닌 곳에 접근시, 홈으로 보냄)
3. 해당 사용자의 페이지인지 확인하는 커스텀 훅
4. 세션 스토리지 사용 -> 스토어의 nickname
#26
> Feature: 라우터, 커스텀 훅

- src/components/auth/SocialLogin.js
> Fix: 환경 변수

- src/router/SettingRoute.js
1. 스토어의 nickname -> session nickname
#94
> Fix: 세팅 라우트 수정

- src/components/auth/SocialLogin.js
> hotfix : naverlogin

- src/components/mypage/MyPageComponent.js
> Fix: 친구 페이지

- src/components/mypage/MyPageComponent.js
1. 페이지 주인과의 관계에 따라 하단 버튼 변경
#100
> Fix: 마이페이지 버튼 변경

- src/components/mypage/MyPageComponent.js
- src/components/select/style.js
이건 확인해주라 너가 만들었던거를 내가 수정하는거라 좀 확인이 필요할듯!
일단 버튼을 안움직이게 놔뒀거든? 어차피 버튼의 역할은 뒤에 캐러셀이 돌던 말던 동일하니까?
그런데 그러면서 포지션을 맞추긴 했는데 조금 불안한 것도 있어서 너가 한번더 보고 체크해주면 좋을듯!
> fix: 시크릿단어 css, 토스트 위로 올리고, 버튼 고정 및 css #93

- src/components/alacard/AlaCardListComponent.js
- src/components/alacard/AlaCardSettingComponent.js
- src/containers/alacard/AlaCardSettingContainer.js
- src/containers/auth/SocialLoginContainer.js
- src/modules/cardSetting.js
> Feature: 카드 미리 보여주기

- src/components/alacard/AlaCardSettingComponent.js
- src/containers/alacard/AlaCardSettingContainer.js
- src/modules/cardSetting.js
> Feature: 토스트 팝업

- src/index.css
> Style: 폰트 수정

- src/components/alacard/AlaCardSettingComponent.js
1. 카드 세팅의 알라 카드에 최소 높이 지정
#127
> Style: 카드 세팅

- src/components/mypage/MyPageComponent.js
- src/components/mypage/style.js
> Style: 알라 카드

- src/components/modal/FriendModal.js
> [STYLE] 친구 알림 스타일 수정

- src/index.css
가끔 cors등 이유로 폰트가 안받아지는 현상 발생
woff2이외에 woff ttf폰도 연결해서 오류 예방
#144 #153
> fix: font-face 수정

- src/components/common/LeftSide.js
- src/components/mypage/MyPageComponent.js
> fix: 비공개 카드 제외

- src/components/profileSettings/ProfileSettingsComponent.js
> [FIX] 프로필 아이콘 수정
